on: push
name: Test on push
jobs:
  aquaLogin:
    name: Aqua login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to aqua saas instance
        id: login
        uses: uniqueck/ga-aqua-login@v1.0.0
        env:
          AQUA_USERNAME: ${{ secrets.AQUA_USERNAME }}
          AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }}
      - name: Log Token
        run: echo "Token ${{ steps.login.outputs.token }}"
      - name: logout from aqua
        uses: ./
        with:
          aqua-token: ${{ steps.login.outputs.token }}
        env:
          NODE_DEBUG: http